version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: npm
    versions:
    - 7.10.0
    - 7.11.0
    - 7.5.6
    - 7.6.0
    - 7.6.1
    - 7.6.2
    - 7.7.0
    - 7.8.0
    - 7.9.0
  - dependency-name: discord.js
    versions:
    - 12.5.1
    - 12.5.2
  - dependency-name: moment
    versions:
    - 2.29.1
